# Die zu verwendenden Simulatoren
devices([
  "iPhone 17 Pro Max"
])

# Die Liste aller 22/25 lokalisierten Sprachen
languages([
  "de", "en"
])

# Das UI-Test-Schema deines Xcode-Projekts
scheme("FamWakeUITests")

# Ordner, in dem die Screenshots gespeichert werden
output_directory("./fastlane/screenshots")

# HTML-Übersicht nach dem Durchlauf anzeigen
skip_open_summary(false)

# Simulatoren vor dem Durchlauf automatisch bereinigen
clear_previous_screenshots(true)
